/**:
    ros__parameters:
        common:
            lid_topic:  "/lidar/scan"
            imu_topic:  "/imu_ekf"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0
        preprocess:
            lidar_type: 2                # 2 for Velodyne LiDAR
            scan_line:  32
            blind: 0.1
            timestamp_unit: 0
            scan_rate: 10
        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     100.0
            extrinsic_est_en:  false
            extrinsic_T: [0.0, 0.0, 0.0]
            extrinsic_R: [ 1.0, 0.0, 0.0,
                           0.0, 1.0, 0.0,
                           0.0, 0.0, 1.0]
        publish:
            path_en: true
            scan_publish_en:  true
            dense_publish_en: true
            scan_bodyframe_pub_en: true
        map_file_path: "/tmp/fastlio_map.pcd"
        pcd_save:
            pcd_save_en: false
            interval: -1
        traj_save:
            traj_save_en: false
            traj_file_path: "/tmp/fastlio_trajectory.txt"
